<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title><?php echo $foo; ?></title>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> 
           <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
var air = (function () {
    var json = null;
    $.ajax({
        'async': false,
        'global': false,
        // your script that outputs json data ...
        'url': "air-as-json",
        'dataType': "json",
        'success': function (data) {
            json = data;
        }
    });
    return json;
})(); 

      function initMap() {
        // Create the map.
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 7,
          center: {lat: 33.9994, lng: -118.213},
          mapTypeId: google.maps.MapTypeId.ROAD
        });

        // Construct the circle for each value in citymap.
        // Note: We scale the area of the circle based on the population.
        for (var data in air) 
        {
          // Add the circle for this city to the map.
          if(10 >= air[data].Air_One)
          {
            var cityCircle = new google.maps.Circle
            (
              {
                strokeColor: '#FF0000',
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: '#FF0000',
                fillOpacity: 0.35,
                map: map,
                center: air[data].center,
                radius: Math.sqrt(air[data].Air_One) * 1000
              }
            );
          }
          else if(20 >= air[data].Air_One)
          {
            var cityCircle = new google.maps.Circle
            (
              {
                strokeColor: '#0000FF',
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: '#0000FF',
                fillOpacity: 0.35,
                map: map,
                center: air[data].center,
                radius: Math.sqrt(air[data].Air_One) * 1000
              }
            );
          }
          else if(50 >= air[data].Air_One)
          {
            var cityCircle = new google.maps.Circle
            (
              {
                strokeColor: '#00FF00',
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: '#00FF00',
                fillOpacity: 0.35,
                map: map,
                center: air[data].center,
                radius: Math.sqrt(air[data].Air_One) * 1000
              }
            );
          }
          
        }
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXMKBcstoboBgrHBcho5saILTBq3PHtPQ&callback=initMap">
    </script>

</body>
</html>