<html>
<body>

<form method="post" action="/upload" enctype="multipart/form-data">
Enter the URL of the PHP script that will receive the CSV file<br />
It should look something like ... http://teama-iot.calit2.net/nicecode/save-csv.php<br />

URL: <input type="text" name="url" size="50" /><br />
<br />
Click 'Browse' to select CSV file to upload to Web Team<br />
<input type="file" name="filename" />
<br />
<input type="submit" value="Send File" />
</form>

</body>
</html>